import { useState, useCallback, useMemo } from 'react';
import { cn } from '@/lib/utils';
import { handleImgError } from '@/utils/handleImgError';

interface BlurImageProps {
  src: string;
  alt: string;
  className?: string;
  containerClassName?: string;
  fallback?: string;
  loading?: 'lazy' | 'eager';
  fetchPriority?: 'high' | 'low' | 'auto';
  onError?: (e: React.SyntheticEvent<HTMLImageElement>) => void;
  style?: React.CSSProperties;
  /** Responsive srcSet for the <img> (overrides the automatic Unsplash srcSet) */
  srcSet?: string;
  /** Explicit WebP srcSet rendered in a <source type="image/webp"> (local images) */
  webpSrcSet?: string;
  /** Sizes attribute for responsive images (e.g., "(max-width: 768px) 100vw, 50vw") */
  sizes?: string;
  /** Explicit intrinsic width for CLS prevention */
  width?: number;
  /** Explicit intrinsic height for CLS prevention */
  height?: number;
  /** Disable the skeleton background (for transparent logos) */
  transparent?: boolean;
}

function isLocal(url: string): boolean {
  return url.startsWith('/');
}

/** Local sibling WebP (e.g. /images/001.jpg -> /images/001.webp). */
function toLocalWebp(url: string): string {
  if (!isLocal(url)) return '';
  return url.replace(/\.(jpe?g|png)$/i, '.webp');
}

/** Unsplash URL with WebP format (they support fm=webp). */
function toUnsplashWebp(url: string): string {
  if (!url.includes('images.unsplash.com')) return '';
  const separator = url.includes('?') ? '&' : '?';
  return `${url}${separator}fm=webp`;
}

export default function BlurImage({
  src,
  alt,
  className,
  containerClassName,
  fallback,
  loading = 'lazy',
  fetchPriority,
  onError,
  style,
  srcSet,
  webpSrcSet,
  sizes,
  width,
  height,
  transparent = false,
}: BlurImageProps) {
  const [isLoaded, setIsLoaded] = useState(false);
  const [hasError, setHasError] = useState(false);

  const handleLoad = useCallback(() => {
    setIsLoaded(true);
  }, []);

  const handleError = useCallback(
    (e: React.SyntheticEvent<HTMLImageElement>) => {
      setHasError(true);
      if (fallback) {
        handleImgError(e, fallback);
        const img = e.currentTarget;
        const retryLoad = () => {
          setIsLoaded(true);
          setHasError(false);
        };
        img.addEventListener('load', retryLoad, { once: true });
      }
      onError?.(e);
    },
    [fallback, onError],
  );

  // WebP source for the primary image. Only emit when it is guaranteed to
  // exist: local paths (generated by scripts/generate-assets.mjs) or Unsplash
  // (format negotiated via fm=webp). Never guess remote .webp URLs.
  const webpSrc = useMemo(() => {
    if (webpSrcSet) return ''; // explicit source set is rendered instead
    const unsplashWebp = toUnsplashWebp(src);
    if (unsplashWebp) return unsplashWebp;
    return toLocalWebp(src);
  }, [src, webpSrcSet]);

  const fallbackWebpSrc = useMemo(() => {
    if (!fallback) return '';
    const unsplashWebp = toUnsplashWebp(fallback);
    if (unsplashWebp) return unsplashWebp;
    return toLocalWebp(fallback);
  }, [fallback]);

  // Automatic responsive srcSet for Unsplash sources
  const autoUnsplashSrcSet = useMemo(() => {
    if (srcSet) return srcSet;
    if (!src.includes('images.unsplash.com')) return '';
    const base = src.split('?')[0];
    const params = new URLSearchParams(src.split('?')[1] || '');
    return [640, 1024, 1440, 1920]
      .map((w) => {
        params.set('w', String(w));
        params.set('fm', 'webp');
        return `${base}?${params.toString()} ${w}w`;
      })
      .join(', ');
  }, [src, srcSet]);

  return (
    <div
      className={cn(
        'relative overflow-hidden',
        !transparent && 'bg-slate-200 dark:bg-slate-800',
        !isLoaded && !hasError && !transparent && 'animate-pulse',
        containerClassName,
      )}
    >
      {/* Skeleton shimmer effect */}
      {!isLoaded && !hasError && (
        <div className="absolute inset-0 -translate-x-full animate-[shimmer_2s_infinite] bg-gradient-to-r from-transparent via-white/20 dark:via-white/5 to-transparent" />
      )}

      <picture>
        {webpSrcSet && <source srcSet={webpSrcSet} type="image/webp" sizes={sizes} />}
        {!webpSrcSet && webpSrc && <source srcSet={webpSrc} type="image/webp" sizes={sizes} />}
        {!webpSrcSet && fallbackWebpSrc && (
          <source srcSet={fallbackWebpSrc} type="image/webp" sizes={sizes} />
        )}

        <img
          src={src}
          alt={alt}
          srcSet={autoUnsplashSrcSet || srcSet}
          sizes={sizes}
          width={width}
          height={height}
          loading={loading}
          fetchPriority={fetchPriority}
          onLoad={handleLoad}
          onError={handleError}
          style={style}
          className={cn(
            'transition-opacity duration-500',
            isLoaded ? 'opacity-100' : 'opacity-0',
            hasError && !fallback ? 'hidden' : '',
            className,
          )}
        />
      </picture>
    </div>
  );
}
